const messages = {
  registeredSuccess: { messaege: 'You are registered successfully' },
  alreadyRegisteredUser: { messaege: 'Already registered' },
  loginSuccess: { messaege: 'You are logged in successfully' },
  loginEmailNotRegistered: { messaege: 'Email not registered' },
  wrongpass: { messaege: 'Password doesnt match' },
  emailReq: { messaege: 'Email id is required' },
  passReq: { messaege: 'Password is required' },
  wrongRole: { messaege: 'Enter valid role' },
  updatedProfile: { messaege: 'Profile successfully updated' },
  invalidCredentials: { messaege: 'Invalid credentials' },
  changePass: { messaege: 'Password changed successfully' },
  unAuthorized: { messaege: 'You are unauthorized!' },
  routeNotFound: { message: 'Route Not Found!' },
  registerSucess: { message: 'Registered succesfully' },
  mandatoryFields: { message: 'Please add all fields' },
  userNotFound: { message: 'User not found' },
  tokenError: { messaege: 'jWT token sign error' },
  controllerError: { message: 'Conroller Error' },
  validationError: { message: 'validation error' },
  middlewareError: { message: 'middleware error' },
  invalidToken: { message: 'invalid token' },
  tokenVerificationError: { message: 'token verification error' },
  userNameNotValid: { sMessage: 'Only one charecter is capital and others are numbers in username' },
  passwordNotValid: { sMessage: 'at least one capital letter, at least one small letter, at least one symbol, total length 16 in password' },
  authFail: { message: 'Authentication fail' },
  userExists: { sMessage: 'this userName already exists' },
  tokenRequire: { sMessage: 'token is require' },
};

module.exports = messages;
